import { c as create_ssr_component } from "../../chunks/ssr.js";
import "../../chunks/client.js";
const css = {
  code: "@keyframes svelte-ydjd51-fade-in{from{opacity:0}}@keyframes svelte-ydjd51-fade-out{to{opacity:0}}@keyframes svelte-ydjd51-slide-from-right{from{transform:translateX(30px)}}@keyframes svelte-ydjd51-slide-to-left{to{transform:translateX(-30px)}}:root::view-transition-old(root){animation:90ms cubic-bezier(0.4, 0, 1, 1) both svelte-ydjd51-fade-out,\r\n			300ms cubic-bezier(0.4, 0, 0.2, 1) both svelte-ydjd51-slide-to-left}:root::view-transition-new(root){animation:210ms cubic-bezier(0, 0, 0.2, 1) 90ms both svelte-ydjd51-fade-in,\r\n			300ms cubic-bezier(0.4, 0, 0.2, 1) both svelte-ydjd51-slide-from-right}",
  map: `{"version":3,"file":"+layout.svelte","sources":["+layout.svelte"],"sourcesContent":["<script>\\r\\n\\timport '../app.css';\\r\\n\\timport { onNavigate } from '$app/navigation';\\r\\n\\timport Lenis from 'lenis';\\r\\n\\timport { onMount } from 'svelte';\\r\\n\\tonMount(() => {\\r\\n\\t\\tconst lenis = new Lenis();\\r\\n\\r\\n\\t\\tlenis.on('scroll', (e) => {\\r\\n\\t\\t\\t// console.log(e);\\r\\n\\t\\t});\\r\\n\\r\\n\\t\\tfunction raf(time) {\\r\\n\\t\\t\\tlenis.raf(time);\\r\\n\\t\\t\\trequestAnimationFrame(raf);\\r\\n\\t\\t}\\r\\n\\r\\n\\t\\trequestAnimationFrame(raf);\\r\\n\\t});\\r\\n\\tonNavigate((navigation) => {\\r\\n\\t\\tif (!document.startViewTransition) return;\\r\\n\\r\\n\\t\\treturn new Promise((resolve) => {\\r\\n\\t\\t\\tdocument.startViewTransition(async () => {\\r\\n\\t\\t\\t\\tresolve();\\r\\n\\t\\t\\t\\tawait navigation.complete;\\r\\n\\t\\t\\t});\\r\\n\\t\\t});\\r\\n\\t});\\r\\n\\texport const prerender = false;\\r\\n<\/script>\\r\\n\\r\\n<slot></slot>\\r\\n\\r\\n<style>\\r\\n\\t@keyframes fade-in {\\r\\n\\t\\tfrom {\\r\\n\\t\\t\\topacity: 0;\\r\\n\\t\\t}\\r\\n\\t}\\r\\n\\r\\n\\t@keyframes fade-out {\\r\\n\\t\\tto {\\r\\n\\t\\t\\topacity: 0;\\r\\n\\t\\t}\\r\\n\\t}\\r\\n\\r\\n\\t@keyframes slide-from-right {\\r\\n\\t\\tfrom {\\r\\n\\t\\t\\ttransform: translateX(30px);\\r\\n\\t\\t}\\r\\n\\t}\\r\\n\\r\\n\\t@keyframes slide-to-left {\\r\\n\\t\\tto {\\r\\n\\t\\t\\ttransform: translateX(-30px);\\r\\n\\t\\t}\\r\\n\\t}\\r\\n\\r\\n\\t:root::view-transition-old(root) {\\r\\n\\t\\tanimation:\\r\\n\\t\\t\\t90ms cubic-bezier(0.4, 0, 1, 1) both fade-out,\\r\\n\\t\\t\\t300ms cubic-bezier(0.4, 0, 0.2, 1) both slide-to-left;\\r\\n\\t}\\r\\n\\r\\n\\t:root::view-transition-new(root) {\\r\\n\\t\\tanimation:\\r\\n\\t\\t\\t210ms cubic-bezier(0, 0, 0.2, 1) 90ms both fade-in,\\r\\n\\t\\t\\t300ms cubic-bezier(0.4, 0, 0.2, 1) both slide-from-right;\\r\\n\\t}\\r\\n</style>\\r\\n"],"names":[],"mappings":"AAmCC,WAAW,qBAAQ,CAClB,IAAK,CACJ,OAAO,CAAE,CACV,CACD,CAEA,WAAW,sBAAS,CACnB,EAAG,CACF,OAAO,CAAE,CACV,CACD,CAEA,WAAW,8BAAiB,CAC3B,IAAK,CACJ,SAAS,CAAE,WAAW,IAAI,CAC3B,CACD,CAEA,WAAW,2BAAc,CACxB,EAAG,CACF,SAAS,CAAE,WAAW,KAAK,CAC5B,CACD,CAEA,KAAK,sBAAsB,IAAI,CAAE,CAChC,SAAS,CACR,IAAI,CAAC,aAAa,GAAG,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,IAAI,CAAC,sBAAQ,CAAC;AACjD,GAAG,KAAK,CAAC,aAAa,GAAG,CAAC,CAAC,CAAC,CAAC,CAAC,GAAG,CAAC,CAAC,CAAC,CAAC,CAAC,IAAI,CAAC,2BAC1C,CAEA,KAAK,sBAAsB,IAAI,CAAE,CAChC,SAAS,CACR,KAAK,CAAC,aAAa,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,GAAG,CAAC,CAAC,CAAC,CAAC,CAAC,IAAI,CAAC,IAAI,CAAC,qBAAO,CAAC;AACtD,GAAG,KAAK,CAAC,aAAa,GAAG,CAAC,CAAC,CAAC,CAAC,CAAC,GAAG,CAAC,CAAC,CAAC,CAAC,CAAC,IAAI,CAAC,8BAC1C"}`
};
const Layout = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  const prerender = false;
  if ($$props.prerender === void 0 && $$bindings.prerender && prerender !== void 0) $$bindings.prerender(prerender);
  $$result.css.add(css);
  return `${slots.default ? slots.default({}) : ``}`;
});
export {
  Layout as default
};
